name: ezy_course
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  http: ^1.3.0
  get: ^4.7.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  skeletonizer: ^1.4.3
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  flutter_phoenix: ^1.1.1
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/