class AppText {
  static String appName = 'ezycourese';
  static String appSlogan = 'The Best Online Learning Platform';
  static String signIn = 'Sign In';
  static String email = 'Email';
  static String password = 'Password';
  static String rememberMe = 'Remember Me';
  static String login = 'Login';
  static String community = 'Community';
  static String logout = 'Logout';
  static String yes = 'Yes';
  static String no = 'No';
  static String enterYourEmail = 'Enter Your email';
  static String errorPasswordMsg = 'Enter password';
  static String pythonDevCommunity = 'Python Developer Community';
  static String writeSomething = 'Write Something here...';
  static String close = 'Close';
  static String createPost = 'Create Post';
  static String create = 'Create';
  static String createPostHint = 'What\'s on your mind?';
  static String day = 'day';
  static String month = 'month';
  static String year = 'year';
  static String second = 'second';
  static String minute = 'minute';
  static String hour = 'hour';
  static String ago = 'ago';
  static String writeComment = 'Write a Comment';
}
